/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author John Victor
 */
public class available extends javax.swing.JFrame {

    static final String USER = "system"; //Database Username
    static final String PASS = "Oracle_2"; //Your Account Password
    static final String DATABASE = "orcl"; //Database Name
    static final String SERVER_IP = "192.168.23.128"; //Your Database Server IP (run ipconfig in cmd)
    static final String PORT = "1521";
    static final String DB_URL = "jdbc:oracle:thin:@" + SERVER_IP + ":" + PORT + ":" +DATABASE;  
    //Create a connection object
    
    /**
     * Creates new form Login
     */
    public available() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        afternoon = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        evening = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        morning = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        home_btn = new javax.swing.JButton();
        booking_btn = new javax.swing.JButton();
        seat_btn = new javax.swing.JButton();
        about_btn = new javax.swing.JButton();
        history_btn = new javax.swing.JButton();
        avail_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(51, 51, 51));
        background.setMaximumSize(new java.awt.Dimension(1370, 633));
        background.setMinimumSize(new java.awt.Dimension(1370, 633));
        background.setPreferredSize(new java.awt.Dimension(1370, 633));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Available Flights");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, -1, 50));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        afternoon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Departure_Time", "Airliner", "Terminal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(afternoon);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 212, 738, 93));

        evening.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Departure_Time", "Airliner", "Terminal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(evening);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 368, 738, 93));

        morning.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Departure_Time", "Airliner", "Terminal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(morning);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 43, 738, 93));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Yu Gothic Light", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("View Available Afternoon Schedules");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Yu Gothic Light", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("View Available Evening Schedules");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setFont(new java.awt.Font("Yu Gothic Light", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("View Available Morning Schedules");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 890, 520));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/booking.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seats.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aboutus.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/history.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flight.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        home_btn.setBackground(new java.awt.Color(0, 153, 153));
        home_btn.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        home_btn.setForeground(new java.awt.Color(255, 255, 255));
        home_btn.setText("Home");
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });
        jPanel1.add(home_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 300, 60));

        booking_btn.setBackground(new java.awt.Color(0, 153, 153));
        booking_btn.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        booking_btn.setForeground(new java.awt.Color(255, 255, 255));
        booking_btn.setText("Booking");
        booking_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booking_btnActionPerformed(evt);
            }
        });
        jPanel1.add(booking_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 300, 60));

        seat_btn.setBackground(new java.awt.Color(0, 153, 153));
        seat_btn.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        seat_btn.setForeground(new java.awt.Color(255, 255, 255));
        seat_btn.setText("Flight Seats");
        seat_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat_btnActionPerformed(evt);
            }
        });
        jPanel1.add(seat_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 300, 60));

        about_btn.setBackground(new java.awt.Color(0, 153, 153));
        about_btn.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        about_btn.setForeground(new java.awt.Color(255, 255, 255));
        about_btn.setText("About Us\n");
        about_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_btnActionPerformed(evt);
            }
        });
        jPanel1.add(about_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 300, 60));

        history_btn.setBackground(new java.awt.Color(0, 153, 153));
        history_btn.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        history_btn.setForeground(new java.awt.Color(255, 255, 255));
        history_btn.setText("Flight History\n");
        history_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                history_btnActionPerformed(evt);
            }
        });
        jPanel1.add(history_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 300, 60));

        avail_btn.setBackground(new java.awt.Color(0, 153, 153));
        avail_btn.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        avail_btn.setForeground(new java.awt.Color(255, 255, 255));
        avail_btn.setText("Available Flights");
        avail_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avail_btnActionPerformed(evt);
            }
        });
        jPanel1.add(avail_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 300, 60));

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 630));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/border.png"))); // NOI18N
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 10, 630));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


               try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(DB_URL, USER, PASS);

            Statement st = con.createStatement();

            String sql = "SELECT * FROM table7";
            ResultSet rs = st.executeQuery(sql);

            DefaultTableModel tblModel = (DefaultTableModel) afternoon.getModel();
            tblModel.setRowCount(0);

            while(rs.next()){
                
                String Date = rs.getString("depdate");
                String Departure_Time = rs.getString("departure");
                String Airliner = rs.getString("airliner");
                String Terminal  = rs.getString("terminal");

                String tbData[] = {Date, Departure_Time,Airliner, Terminal};

                tblModel.addRow(tbData);
            }
            con.close();
        }

        catch (Exception e){
            System.out.println(e.getMessage());
        }



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

               try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(DB_URL, USER, PASS);

            Statement st = con.createStatement();

            String sql = "SELECT * FROM table8";
            ResultSet rs = st.executeQuery(sql);

            DefaultTableModel tblModel = (DefaultTableModel) evening.getModel();
            tblModel.setRowCount(0);

            while(rs.next()){
                
                String Date = rs.getString("depdate");
                String Departure_Time = rs.getString("departure");
                String Airliner = rs.getString("airliner");
                String Terminal  = rs.getString("terminal");

                String tbData[] = {Date, Departure_Time,Airliner, Terminal};

                tblModel.addRow(tbData);
            }
            con.close();
        }

        catch (Exception e){
            System.out.println(e.getMessage());
        }



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        
try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(DB_URL, USER, PASS);

            Statement st = con.createStatement();

            String sql = "SELECT * FROM table9";
            ResultSet rs = st.executeQuery(sql);

            DefaultTableModel tblModel = (DefaultTableModel) morning.getModel();
            tblModel.setRowCount(0);

            while(rs.next()){
                
                String Date = rs.getString("depdate");
                String Departure_Time = rs.getString("departure");
                String Airliner = rs.getString("airliner");
                String Terminal  = rs.getString("terminal");

                String tbData[] = {Date, Departure_Time,Airliner, Terminal};

                tblModel.addRow(tbData);
            }
            con.close();
        }

        catch (Exception e){
            System.out.println(e.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void seat_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat_btnActionPerformed
        new seatings().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_seat_btnActionPerformed

    private void about_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_btnActionPerformed
        new AboutUs().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_about_btnActionPerformed

    private void booking_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booking_btnActionPerformed
        new data().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_booking_btnActionPerformed

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_home_btnActionPerformed

    private void history_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_history_btnActionPerformed
        new History().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_history_btnActionPerformed

    private void avail_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avail_btnActionPerformed
        new available().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_avail_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(available.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(available.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(available.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(available.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new available().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton about_btn;
    private javax.swing.JTable afternoon;
    private javax.swing.JButton avail_btn;
    private javax.swing.JPanel background;
    private javax.swing.JButton booking_btn;
    private javax.swing.JTable evening;
    private javax.swing.JButton history_btn;
    private javax.swing.JButton home_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable morning;
    private javax.swing.JButton seat_btn;
    // End of variables declaration//GEN-END:variables
}
