import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author JJVT
 */
public class History extends javax.swing.JFrame {

  static final String USER = "system"; //Database Username
    static final String PASS = "Oracle_2"; //Your Account Password
    static final String DATABASE = "orcl"; //Database Name
    static final String SERVER_IP = "192.168.23.128"; //Your Database Server IP (run ipconfig in cmd)
    static final String PORT = "1521";
    static final String DB_URL = "jdbc:oracle:thin:@" + SERVER_IP + ":" + PORT + ":" +DATABASE;    
    
    Connection conn = null;
    Statement stmt = null;

    public History() {
       initComponents();
       this.setLocationRelativeTo(null);
       TableColumnModel tcm = formtbl.getColumnModel();
       updateTable();

    }
public void updateTable() {
        try {
		conn = DriverManager.getConnection(DB_URL, USER, PASS);
		String sql = "SELECT * from flights";
		PreparedStatement ps = conn.prepareStatement(sql);
		ResultSet rs = ps.executeQuery();
		DefaultTableModel tm = (DefaultTableModel) formtbl.getModel();
		tm.setRowCount(0);
		while (rs.next()) {
			Object row[] = {
				rs.getInt("flight_id"),
				rs.getString("firstname"),
				rs.getString("lastname"),
				rs.getString("flightclass"),
				rs.getString("origin"),
				rs.getString("destination"),
                                rs.getString("departure"),
                                rs.getString("seatno"),
                                rs.getString("price"),
			};
			tm.addRow(row);
		}

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        id_txt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        delete_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        lastname_txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        formtbl = new javax.swing.JTable();
        refresh_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        departure_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstname_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        search_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        return_btn = new javax.swing.JButton();
        class_combo = new javax.swing.JComboBox<>();
        origin_combo = new javax.swing.JComboBox<>();
        destination_combo = new javax.swing.JComboBox<>();
        seat_combo = new javax.swing.JComboBox<>();
        price_combo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id_txt.setBackground(new java.awt.Color(51, 51, 51));
        id_txt.setForeground(new java.awt.Color(0, 204, 204));
        id_txt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 204, 204)));
        id_txt.setEnabled(false);
        id_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_txtActionPerformed(evt);
            }
        });
        getContentPane().add(id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 28, 22, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete_btn.setBackground(new java.awt.Color(0, 204, 204));
        delete_btn.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(255, 255, 255));
        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        jPanel1.add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 100, 30));

        clear_btn.setBackground(new java.awt.Color(0, 204, 204));
        clear_btn.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        clear_btn.setForeground(new java.awt.Color(255, 255, 255));
        clear_btn.setText("Clear");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });
        jPanel1.add(clear_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 100, 30));

        update_btn.setBackground(new java.awt.Color(0, 204, 204));
        update_btn.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        update_btn.setForeground(new java.awt.Color(255, 255, 255));
        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        jPanel1.add(update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 100, 30));

        lastname_txt.setBackground(new java.awt.Color(51, 51, 51));
        lastname_txt.setForeground(new java.awt.Color(0, 204, 204));
        lastname_txt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 204, 204)));
        lastname_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastname_txtActionPerformed(evt);
            }
        });
        jPanel1.add(lastname_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 200, -1));

        formtbl.setBackground(new java.awt.Color(0, 204, 204));
        formtbl.setForeground(new java.awt.Color(51, 51, 51));
        formtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight ID", "First Name", "Last Name", "Flight Class", "Origin", "Destination", "Departure Date", "Seat No.", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        formtbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formtblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(formtbl);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 770, 380));

        refresh_btn.setBackground(new java.awt.Color(0, 204, 204));
        refresh_btn.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        refresh_btn.setForeground(new java.awt.Color(255, 255, 255));
        refresh_btn.setText("Refresh");
        refresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_btnActionPerformed(evt);
            }
        });
        jPanel1.add(refresh_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 480, 100, 30));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Departure Date:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        departure_txt.setBackground(new java.awt.Color(51, 51, 51));
        departure_txt.setForeground(new java.awt.Color(0, 204, 204));
        departure_txt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 204, 204)));
        jPanel1.add(departure_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 270, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 204));
        jLabel7.setText("Flight No.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("Origin:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("Destination:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("First Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        firstname_txt.setBackground(new java.awt.Color(51, 51, 51));
        firstname_txt.setForeground(new java.awt.Color(0, 204, 204));
        firstname_txt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 204, 204)));
        firstname_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstname_txtActionPerformed(evt);
            }
        });
        jPanel1.add(firstname_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 200, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Last Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("Flight Class:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        search_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_txtActionPerformed(evt);
            }
        });
        search_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_txtKeyReleased(evt);
            }
        });
        jPanel1.add(search_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, 203, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 204));
        jLabel8.setText("Search");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 204));
        jLabel9.setText("Seat No.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 204));
        jLabel10.setText("Price:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 30, -1));

        return_btn.setBackground(new java.awt.Color(51, 51, 51));
        return_btn.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        return_btn.setForeground(new java.awt.Color(0, 204, 204));
        return_btn.setText("Return");
        return_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_btnActionPerformed(evt);
            }
        });
        jPanel1.add(return_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        class_combo.setBackground(new java.awt.Color(0, 204, 204));
        class_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economy", "Business", "First Class" }));
        jPanel1.add(class_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 270, -1));

        origin_combo.setBackground(new java.awt.Color(0, 204, 204));
        origin_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BXU", "CBO", "CLARK", "DGT", "DPL", "IAO", "LGP", "NAIA", "OZC", "RXS", "TUG", "USU" }));
        jPanel1.add(origin_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 270, -1));

        destination_combo.setBackground(new java.awt.Color(0, 204, 204));
        destination_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BXU", "CBO", "CLARK", "DGT", "DPL", "IAO", "LGP", "NAIA", "OZC", "RXS", "TUG", "USU" }));
        jPanel1.add(destination_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 270, -1));

        seat_combo.setBackground(new java.awt.Color(0, 204, 204));
        seat_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F1", "F2", "F3", "F4", "F5", "F6", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "E1", "E2", "E3", "E4", "E5", "E6", "E7", "E8", "E9", "E10", "E11", "E12", "E13", "E14", "E15", "E16", "E17", "E18", "E19", "E20" }));
        jPanel1.add(seat_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 90, -1));

        price_combo.setBackground(new java.awt.Color(0, 204, 204));
        price_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2,000", "6,000", "11,000" }));
        price_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price_comboActionPerformed(evt);
            }
        });
        jPanel1.add(price_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 80, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_txtActionPerformed
   


    }//GEN-LAST:event_search_txtActionPerformed

    private void refresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_btnActionPerformed
      try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(DB_URL, USER, PASS);

            Statement st = con.createStatement();

            String sql = "SELECT * FROM flights ORDER BY flight_id ASC";
            ResultSet rs = st.executeQuery(sql);

            DefaultTableModel flights = (DefaultTableModel) formtbl.getModel();
            flights.setRowCount(0);

            while(rs.next()){
                String firstname_txt = rs.getString("firstname");
                String lastname_txt = rs.getString("lastname");
                String fclass_txt = rs.getString("flightclass");
                String origin_txt  = rs.getString("origin");
                String destination_txt = rs.getString("destination");
                String departure_txt = rs.getString("departure");
                String seat_txt = rs.getString("seatno");
                String price_txt = rs.getString("price");
                String id_txt = String.valueOf(rs.getInt("flight_id"));

                String tbData[] = {id_txt, firstname_txt, lastname_txt, fclass_txt, origin_txt, destination_txt, departure_txt};

                flights.addRow(tbData);
            }
            con.close();
        }

        catch (Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_refresh_btnActionPerformed

    private void search_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_txtKeyReleased
        String keyword = search_txt.getText();
try {
	conn = DriverManager.getConnection(DB_URL, USER, PASS);
	String sql = "SELECT * FROM flights WHERE flight_id like '%" + keyword + "%' OR lastname like '%" + keyword + "%'";
	PreparedStatement ps = conn.prepareStatement(sql);
	ResultSet rs = ps.executeQuery();
	DefaultTableModel tm = (DefaultTableModel) formtbl.getModel();
	tm.setRowCount(0);
	while (rs.next()) {
		Object row[] = {
			rs.getInt("flight_id"),
			rs.getString("firstname"),
			rs.getString("lastname"),
			rs.getString("flightclass"),
			rs.getString("origin"),
			rs.getString("destination"),
                        rs.getString("departure"),
                        rs.getString("seatno"),
                        rs.getString("price"),
                       
		};
		tm.addRow(row);
	}
} catch (Exception e) {
	System.out.println(e);
}


    }//GEN-LAST:event_search_txtKeyReleased

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        try {
    
           Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
                String sql = "UPDATE flights SET firstname = ?, lastname = ?, flightclass = ?, origin = ?, destination = ?, departure = ?, seatno = ?, price = ? WHERE flight_id = ?";
                PreparedStatement stmnt = conn.prepareStatement(sql);
            stmnt.setString(1, firstname_txt.getText());
            stmnt.setString(2, lastname_txt.getText());
            stmnt.setString(3, (String) class_combo.getSelectedItem());
            stmnt.setString(4, (String) origin_combo.getSelectedItem());
            stmnt.setString(5, (String) destination_combo.getSelectedItem());
            stmnt.setString(6,  departure_txt.getText());
            stmnt.setString(7, (String) seat_combo.getSelectedItem());
            stmnt.setString(8, (String) price_combo.getSelectedItem());
            stmnt.setString(9, id_txt.getText());
            stmnt.executeUpdate();
            jOptionPane1.showMessageDialog(null, "Updated records successfully");
            updateTable();
            conn.close();
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_update_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed

        id_txt.setText(null);
        firstname_txt.setText(null);
        lastname_txt.setText(null);
        class_combo.setSelectedItem(null);
        origin_combo.setSelectedItem(null);
        destination_combo.setSelectedItem(null);
        departure_txt.setText(null);
        seat_combo.setSelectedItem(null);
        price_combo.setSelectedItem(null);
    }//GEN-LAST:event_clear_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        try {
            int id = Integer.parseInt(id_txt.getText());
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();
            String sql = "DELETE from flights where flight_id = " + id;
            if (jOptionPane1.showConfirmDialog(null, "Confirm delete?") == jOptionPane1.YES_OPTION) {
                stmt.executeUpdate(sql);
                updateTable();
                jOptionPane1.showMessageDialog(null, "Deleted successfully");
            }
            conn.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void return_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_btnActionPerformed
       new Menu().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_return_btnActionPerformed

    private void price_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price_comboActionPerformed

    private void formtblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formtblMouseClicked
        DefaultTableModel tm = (DefaultTableModel) formtbl.getModel();
        int selectedRowIndex = formtbl.getSelectedRow();
        id_txt.setText(tm.getValueAt(selectedRowIndex, 0).toString());
        firstname_txt.setText(tm.getValueAt(selectedRowIndex, 1).toString());
        lastname_txt.setText(tm.getValueAt(selectedRowIndex, 2).toString());
        class_combo.setSelectedItem(tm.getValueAt(selectedRowIndex, 3).toString());
        origin_combo.setSelectedItem(tm.getValueAt(selectedRowIndex, 4).toString());
        destination_combo.setSelectedItem(tm.getValueAt(selectedRowIndex, 5).toString());
        departure_txt.setText(tm.getValueAt(selectedRowIndex, 6).toString());
        seat_combo.setSelectedItem(tm.getValueAt(selectedRowIndex, 7).toString());
        price_combo.setSelectedItem(tm.getValueAt(selectedRowIndex, 8).toString());
    }//GEN-LAST:event_formtblMouseClicked

    private void lastname_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastname_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastname_txtActionPerformed

    private void firstname_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstname_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstname_txtActionPerformed

    private void id_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new History().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> class_combo;
    private javax.swing.JButton clear_btn;
    private javax.swing.JButton delete_btn;
    public static javax.swing.JTextField departure_txt;
    public static javax.swing.JComboBox<String> destination_combo;
    public static javax.swing.JTextField firstname_txt;
    private javax.swing.JTable formtbl;
    public static javax.swing.JTextField id_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField lastname_txt;
    public static javax.swing.JComboBox<String> origin_combo;
    public static javax.swing.JComboBox<String> price_combo;
    private javax.swing.JButton refresh_btn;
    private javax.swing.JButton return_btn;
    private javax.swing.JTextField search_txt;
    public static javax.swing.JComboBox<String> seat_combo;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
